const START_LOAD_PLAYLIST = 'START_LOAD_PLAYLIST';
const LOAD_PLAYLIST_SUCCESS = 'LOAD_PLAYLIST_SUCCESS';
const LOAD_PLAYLIST_FAILED = 'LOAD_PLAYLIST_FAILED';

export {
  START_LOAD_PLAYLIST,
  LOAD_PLAYLIST_SUCCESS,
  LOAD_PLAYLIST_FAILED
};
